### ISSUE TITLE
All __pycache__/ dir should be deleted for github repo

### ISSUE THREAD

**Issue by shriekdj** [Rashed360/django-blog-project#6]
the cache is not needed to uploaded to github please remove it.

**Comment by shriekdj** [comment]
This Cache files are automatically created automatically by python for the given operating system it is running in so it will create issues in deploying to other locations

**Comment by shriekdj** [comment]
What happened @Rashed360

**Comment by Rashed360** [comment]
I have merged your commits.

**Comment by shriekdj** [comment]
ok👌
